apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-service
  description: "An example service."
  tags:
    - java
    - spring-boot
spec:
  type: service
  lifecycle: experimental
  owner: team-example
